<script>
  //Ja täällä on listana generoinnissa käytettävät sukunimet ja tittelit
  export const sukunimet = [
    'of Astora',
    'of Catarina',
    'of Nokstella',
    'of Oolacile',
    'of Lordan',
    'of Majula',
    'of Stormhill',
    'of Nokron',
    'of Leyndell',
    'of Limgrave',
    'of Caelid',
    'of Boletaria',
    'of Farum Azula',
    'of Carim',
    'of Meridia',
    'of Rivia',
    'of Riverwood',
    'of Whiterun',
    'of Windhelm',
    'of Irithyll',
    'Armstrong',
    'Belmont',
    'Williamson',
    'Morrison',
    'Baker',
    'Edwards',
    'Fitzgerald',
    'Chamberlain',
    'Achard',
    'Albelin',
    'Altard',
    'Aguilon',
    'Alis',
    'Flambard',
    'Faucon',
    'Fresle',
    'Fromentin',
    'Fitzhugh',
    'Gillain',
    'Grai',
    'Ansgot',
    'Azor',
    'Basset',
    'Tristram',
    'Bohon',
    'Highrise',
    'Bolbec',
    'Cairon',
    'Carnet',
    'Hawthorne',
    'Mortimer',
    'Vale',
    'Calmette',
    'Houndmoor',
    'Cardonell',
    'Cherbourg',
    'Colleville',
    'Danvers',
    'Desmares',
    'Ditton',
    'Hemingway',
    'Codsworth',
    'Felvidek',
    'Strife',
    'Leonhart',
    'Castello',
    'Auditore',
    'Mordhau',
    'Hayden',
    'Woodville',
    'Fairfax',
    'Somneri',
    'Reviers',
    'Orlebar',
    'Murdac',
    'Mortagne',
    'Monceaux',
    'Morphew',
    'Montaigu',
    'Mercier',
    'Highwind',
    'the Great',
    'the Magnificent',
    'the Conqueror',
    'The Warrior',
    'the Terrible',
    'the Blasphemous',
    'the Blessed',
    'the Invincible',
    'the Warmaster',
    'the Honored',
    'the Virtuous',
    'the Sinner',
    'the Ruthless',
    'the Pure',
    'the Sunlight',
    'the Fallen',
    'the Destroyer',
    'the Unifier',
    'the Loved',
    'the Lightbringer',
    'the Shadowbringer',
    'the Brutal',
    'the Kind',
  ];
</script>
